ground:
    width: 10
    height: 20
    flat: True

components:

#  - type: {'reference': 'box', 'object': 'primative'}
#    size: {'x': 1.0, 'y': 1.0, 'z': 1.0}
#    position: {'x': 0.0, 'y': 0.0, 'z': 0.0}
#    orientation: {'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0}

#  - type: {'reference': 'box', 'object': 'primative'}
#    size: {'x': 2.0, 'y': 0.5, 'z': 1.0}

#  - type: {'reference': 'tree.yaml', 'object': 'custom'}
  - type: {'reference': 'shade.yaml', 'object': 'custom'}
    anchor: {'pose', 'orientation'}
