components:

  - type: {'reference': 'plane', 'object': 'primative'}
    width: 100.0
    length: 100.0
    material: {'name': 'DarkGrey'}

#  - type: {'reference': 'column_connections.yaml', 'object': 'custom'}
#    anchor:
#      position: {'x': -10, 'y': 6.0}
#  - type: {'reference': 'column_connections.yaml', 'object': 'custom'}
#    anchor:
#      position: {'x': -8, 'y': 6.0}
#  - type: {'reference': 'column_connections.yaml', 'object': 'custom'}
#    anchor:
#      position: {'x': -6, 'y': 6.0}
#  - type: {'reference': 'column_connections.yaml', 'object': 'custom'}
#    anchor:
#      position: {'x': -4, 'y': 6.0}
#  - type: {'reference': 'column_connections.yaml', 'object': 'custom'}
#    anchor:
#      position: {'x': -2, 'y': 6.0}

  - type: {'reference': 'double_structure.yaml', 'object': 'custom'}
    anchor:
      position: {'x': 0.0, 'y': 0.0}
      orientation: {'yaw': 0.0}
