components:

  # Floor
  - type: {'reference': 'plane', 'object': 'primative'}
    position: {'x': 0.0, 'y': 0.0, 'z': 0.01}
    width: 7.2
    length: 52.8
    material: {'name': 'Grey'}

  # Bed
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -2.40, 'y': 0.0, 'z': 0.2}
    size: {'x': 0.8, 'y': 44.8, 'z': 0.4}
    material: {'name': 'GreenTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -0.80, 'y': 0.0, 'z': 0.2}
    size: {'x': 0.8, 'y': 44.8, 'z': 0.4}
    material: {'name': 'GreenTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.80, 'y': 0.0, 'z': 0.2}
    size: {'x': 0.8, 'y': 44.8, 'z': 0.4}
    material: {'name': 'GreenTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 2.40, 'y': 0.0, 'z': 0.2}
    size: {'x': 0.8, 'y': 44.8, 'z': 0.4}
    material: {'name': 'GreenTransparent'}


  # Flooring (ends)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.0, 'y': 24.8, 'z': 0.2}
    size: {'x': 7.2, 'y': 3.2, 'z': 0.4}
    material: {'name': 'Blue'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.0, 'y': -24.8, 'z': 0.2}
    size: {'x': 7.2, 'y': 3.2, 'z': 0.4}
    material: {'name': 'Blue'}


  # Tarp (side)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 3.6, 'y': 0.0, 'z': 0.875}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.75}
    material: {'name': 'BlackTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -3.6, 'y': 0.0, 'z': 0.875}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.75}
    material: {'name': 'BlackTransparent'}


  # Tarp (end)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.0, 'y': 26.4, 'z': 0.875}
    size: {'x': 7.2, 'y': 0.025, 'z': 1.75}
    material: {'name': 'BlackTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.0, 'y': -26.4, 'z': 0.875}
    size: {'x': 7.2, 'y': 0.025, 'z': 1.75}
    material: {'name': 'BlackTransparent'}









##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################

  # Poles (tall)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 1.2, 'y': 26.4, 'z': 1.75}
    radius: 0.025
    length: 2.7
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -1.2, 'y': 26.4, 'z': 1.75}
    radius: 0.025
    length: 2.7
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 2.0, 'y': 26.4, 'z': 1.525}
    radius: 0.025
    length: 2.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -2.0, 'y': 26.4, 'z': 1.525}
    radius: 0.025
    length: 2.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 2.8, 'y': 26.4, 'z': 1.3}
    radius: 0.025
    length: 1.8
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -2.8, 'y': 26.4, 'z': 1.3}
    radius: 0.025
    length: 1.8
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 3.6, 'y': 26.4, 'z': 1.075}
    radius: 0.025
    length: 1.35
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -3.6, 'y': 26.4, 'z': 1.075}
    radius: 0.025
    length: 1.35
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': 26.4, 'z': 3.1}
    radius: 0.025
    length: 2.45
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}

  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.4, 'y': 26.4, 'z': 3.225}
    radius: 0.025
    length: 0.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.4, 'y': 26.4, 'z': 3.225}
    radius: 0.025
    length: 0.25

  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': 26.4, 'z': 3.3}
    radius: 0.025
    length: 0.8
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': 26.4, 'z': 3.45}
    radius: 0.025
    length: 0.25

  # Poles (door)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.02, 'y': 26.4, 'z': 1.75}
    radius: 0.025
    length: 2.75
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.02, 'y': 26.4, 'z': 1.75}
    radius: 0.025
    length: 2.75
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.625, 'y': 26.4, 'z': 1.3}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.625, 'y': 26.4, 'z': 1.3}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.625, 'y': 26.4, 'z': 2.2}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.625, 'y': 26.4, 'z': 2.2}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.625, 'y': 26.4, 'z': 3.1}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.625, 'y': 26.4, 'z': 3.1}
    radius: 0.025
    length: 1.2
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}








##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################

  # Poles (tall)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 1.2, 'y': -26.4, 'z': 1.75}
    radius: 0.025
    length: 2.7
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -1.2, 'y': -26.4, 'z': 1.75}
    radius: 0.025
    length: 2.7
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 2.0, 'y': -26.4, 'z': 1.525}
    radius: 0.025
    length: 2.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -2.0, 'y': -26.4, 'z': 1.525}
    radius: 0.025
    length: 2.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 2.8, 'y': -26.4, 'z': 1.3}
    radius: 0.025
    length: 1.8
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -2.8, 'y': -26.4, 'z': 1.3}
    radius: 0.025
    length: 1.8
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 3.6, 'y': -26.4, 'z': 1.075}
    radius: 0.025
    length: 1.35
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -3.6, 'y': -26.4, 'z': 1.075}
    radius: 0.025
    length: 1.35
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': -26.4, 'z': 3.1}
    radius: 0.025
    length: 2.45
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}

  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.4, 'y': -26.4, 'z': 3.225}
    radius: 0.025
    length: 0.25
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.4, 'y': -26.4, 'z': 3.225}
    radius: 0.025
    length: 0.25

  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': -26.4, 'z': 3.3}
    radius: 0.025
    length: 0.8
    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': -26.4, 'z': 3.45}
    radius: 0.025
    length: 0.25

#  # Poles (door)
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': 0.02, 'y': -26.4, 'z': 1.75}
#    radius: 0.025
#    length: 2.75
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': -0.02, 'y': -26.4, 'z': 1.75}
#    radius: 0.025
#    length: 2.75
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': 0.625, 'y': -26.4, 'z': 1.3}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': -0.625, 'y': -26.4, 'z': 1.3}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': 0.625, 'y': -26.4, 'z': 2.2}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': -0.625, 'y': -26.4, 'z': 2.2}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': 0.625, 'y': -26.4, 'z': 3.1}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': 1.57, 'yaw': 0.0}
#  - type: {'reference': 'cylinder', 'object': 'primative'}
#    position: {'x': -0.625, 'y': -26.4, 'z': 3.1}
#    radius: 0.025
#    length: 1.2
#    orientation: {'roll': 0.0, 'pitch': -1.57, 'yaw': 0.0}










##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################




  # Tarp (left top)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 2.95, 'y': 0.0, 'z': 2.2}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.6}
    orientation: {'roll': 0.0, 'pitch': -0.95, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 1.75, 'y': 0.0, 'z': 2.9}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.2}
    orientation: {'roll': 0.0, 'pitch': -1.15, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.75, 'y': 0.0, 'z': 3.25}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.0}
    orientation: {'roll': 0.0, 'pitch': -1.35, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}

  # Tarp (right top)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -2.95, 'y': 0.0, 'z': 2.2}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.6}
    orientation: {'roll': 0.0, 'pitch': 0.95, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -1.75, 'y': 0.0, 'z': 2.9}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.2}
    orientation: {'roll': 0.0, 'pitch': 1.15, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -0.75, 'y': 0.0, 'z': 3.25}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.0}
    orientation: {'roll': 0.0, 'pitch': 1.35, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}


  # Tarp Second
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.5, 'y': 0.0, 'z': 3.45}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.0}
    orientation: {'roll': 0.0, 'pitch': -1.35, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': -0.5, 'y': 0.0, 'z': 3.45}
    size: {'x': 0.025, 'y': 52.8, 'z': 1.0}
    orientation: {'roll': 0.0, 'pitch': 1.35, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}



#Side Panels
# width = 0.80
# height = 1.35
# total = 66
#  x1 electrics panel
#  x2 resivour panel
#  x1 pump panel
#  x1 track change panel
#  x56 bed panels
#  x1 track change panel
#  x1 pump panel
#  x2 resivour panel
#  x1 electrics panel

#Bed
# 0.80 width
# 0.40 height
# 56*panelswidth length

#Track
# 0.80 wide

#Floor
# 4*bedwidth + 5*trackwidth = 7.20 width
# 66*panelwidth = 52.8 length

#Door (x2 sliding)
# 2.70 tall
# 1.25 wide each

#Panel above door
# 0.40 tall

# Second shelter
# 0.40 tall

# Sides:
# totalsidepanels * sidepanelwidth = 52.8m
# starts at bed height so 0.4 up from floor (same height as bed)

# Blue end
# 4panel * panelwidth = 3.2m
# 31 * bedwidth80 = 12.4







