components:

  # Poles (tall)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 1.0, 'y': 5.0, 'z': 0.5}
    radius: 0.025
    length: 1.0
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 1.0, 'y': -5.0, 'z': 0.5}
    radius: 0.025
    length: 1.0

  # Poles (mid)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.25, 'y': 5.0, 'z': 0.66}
    radius: 0.025
    length: 1.32
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -0.25, 'y': -5.0, 'z': 0.66}
    radius: 0.025
    length: 1.32

  # Poles (short)
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -1.0, 'y': 5.0, 'z': 0.75}
    radius: 0.025
    length: 1.5
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': -1.0, 'y': -5.0, 'z': 0.75}
    radius: 0.025
    length: 1.5

  # Tarp (top)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.0, 'y': 0.0, 'z': 1.25}
    size: {'x': 0.015, 'y': 10.0, 'z': 2.15}
    orientation: {'roll': 0.0, 'pitch': -1.3, 'yaw': 0.0}
    material: {'name': 'BlueTransparentOverlay'}

  # Tarp (ends)
  - type: {'reference': 'box', 'object': 'primative'}
    size: {'x': 1.25, 'y': 0.015, 'z': 1.0}
    position: {'x': 0.35, 'y': 5.0, 'z': 0.5}
    material: {'name': 'BlackTransparent'}
  - type: {'reference': 'box', 'object': 'primative'}
    size: {'x': 1.25, 'y': 0.015, 'z': 1.0}
    position: {'x': 0.35, 'y': -5.0, 'z': 0.5}
    material: {'name': 'BlackTransparent'}

  # Tarp (back)
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 1.0, 'y': 0.0, 'z': 0.5}
    size: {'x': 0.025, 'y': 10.0, 'z': 1.0}
    material: {'name': 'BlackTransparent'}

  # Bed
  - type: {'reference': 'box', 'object': 'primative'}
    position: {'x': 0.45, 'y': 0.0, 'z': 0.075}
    size: {'x': 1.0, 'y': 10.0, 'z': 0.15}
    material: {'name': 'GreenTransparent'}
