name: 'tree'
description: 'simple rubber tree'

components:
  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': 0.0, 'z': 3.0}
    material: {'name': 'WoodPallet'}
    radius: 0.12
    length: 6.0

  - type: {'reference': 'cylinder', 'object': 'primative'}
    position: {'x': 0.0, 'y': 0.0, 'z': 6.25}
    material: {'name': 'GreenTransparent'}
    radius: 2.5
    length: 0.5

#5.0m column
#0.18m tree radius
#3.0m row
