name: 'tree'
description: 'simple rubber tree'

components:
  - type: {'reference': 'cylinder', 'object': 'primative'}
    size: {'x': 0.0, 'y': 0.0, 'z': 0.0}
    position: {'x': 0.0, 'y': 0.0, 'z': 1.0}
    orientation: {'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0}
    radius: 0.2
    length: 1
    name: 'tree'
